### ISSUE TITLE
go get遇错

### ISSUE THREAD

**Issue by briteming** [yuanrenguang715/socks5-proxy#1]
hi.

go get -u -v github.com/yuanrenguang715/socks5-proxy/client/
它显示：
github.com/yuanrenguang715/socks5-proxy (download)
package socks5-proxy-dende/utils/config: unrecognized import path "socks5-proxy-dende/utils/config" (import path does not begin with hostname)
package socks5-proxy-dende/utils/logger: unrecognized import path "socks5-proxy-dende/utils/logger" (import path does not begin with hostname)

如何解决？

**Comment by yuanrenguang715** [comment]
建议使用git clone，你go get 到client  但是它依赖config，logger   import我使用的自己的路径，

**Comment by yuanrenguang715** [comment]
utils 我将开放出来提供给到你

**Comment by yuanrenguang715** [comment]
https://github.com/yuanrenguang715/utils

**Comment by briteming** [comment]
还是弄不明白。可以把import路径改为对用户友好的路径吗

**Comment by yuanrenguang715** [comment]
很久没更新了，你下载下来更新一下   git   clone

**Comment by briteming** [comment]
hi.

yudeMacBook-Air:~ brite$ git clone https://github.com/yuanrenguang715/socks5-proxy socks5-proxy-by-yuanrenguang715
Cloning into 'socks5-proxy-by-yuanrenguang715'...
remote: Enumerating objects: 48, done.
remote: Total 48 (delta 0), reused 0 (delta 0), pack-reused 48
Unpacking objects: 100% (48/48), done.
Checking connectivity... done.
yudeMacBook-Air:~ brite$ cd socks5-proxy-by-yuanrenguang715
yudeMacBook-Air:socks5-proxy-by-yuanrenguang715 brite$ git pull
Already up-to-date.
yudeMacBook-Air:socks5-proxy-by-yuanrenguang715 brite$ cd client
yudeMacBook-Air:client brite$ ls
client.go	client.key	client.pem	config.ini
yudeMacBook-Air:client brite$ go build
client.go:10:2: cannot find package "socks5-proxy-dende/utils/config" in any of:
	/Users/brite/go1.13/go/src/socks5-proxy-dende/utils/config (from $GOROOT)
	/Users/brite/go1.13/go/gopath/src/socks5-proxy-dende/utils/config (from $GOPATH)
client.go:11:2: cannot find package "socks5-proxy-dende/utils/logger" in any of:
	/Users/brite/go1.13/go/src/socks5-proxy-dende/utils/logger (from $GOROOT)
	/Users/brite/go1.13/go/gopath/src/socks5-proxy-dende/utils/logger (from $GOPATH)
yudeMacBook-Air:client brite$

还是不行啊。怎么解决？

**Comment by yuanrenguang715** [comment]
![2020-05-12 11-06-49屏幕截图](https://user-images.githubusercontent.com/39899288/81634119-dfb1a300-9440-11ea-8d90-e9d66f7384ba.png)

**Comment by yuanrenguang715** [comment]
你的go环境没有搭建好，检查你的go环境

**Comment by yuanrenguang715** [comment]
没有使用go mod的情况下设置你的gopth   clone 的时候不要重命名   你试下

**Comment by briteming** [comment]
我的go环境搭建好了。我go get其他项目没问题。我cd 某些项目里面，进行go build也没问题。只是上面显示的socks5-proxy-dende是个什么目录，你的源代码中是不是写错了？是不是应该写为socks5-proxy？

**Comment by yuanrenguang715** [comment]
项目名改为socks5-proxy-dende就可以了

**Comment by yuanrenguang715** [comment]
我自己编译了一下   是go版本问题   是否使用了go mod   我更新代码    你稍后下载

**Comment by yuanrenguang715** [comment]
现在克隆下来即可编译    使用了go mod 管理

**Comment by briteming** [comment]
now it's ok.
thank u.

**Comment by briteming** [comment]
hi.

今天我运行程序，遇错：
client-based-on-socks5-proxy-by-yuanrenguang715
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x1 pc=0x11fe853]

goroutine 1 [running]:
github.com/go-ini/ini.(*File).SectionsByName(0x0, 0x1280367, 0x7, 0x0, 0x0, 0x0, 0x0, 0x0)
	/Users/briteming/go1.13/go/gopath/pkg/mod/github.com/go-ini/ini@v1.56.0/file.go:147 +0x73
github.com/go-ini/ini.(*File).GetSection(...)
	/Users/briteming/go1.13/go/gopath/pkg/mod/github.com/go-ini/ini@v1.56.0/file.go:134
github.com/go-ini/ini.(*File).Section(0x0, 0x1280367, 0x7, 0x0)
	/Users/briteming/go1.13/go/gopath/pkg/mod/github.com/go-ini/ini@v1.56.0/file.go:166 +0x43
utils/config.ClientConfig(0xc000086058)
	/Users/briteming/socks5-proxy-by-yuanrenguang715/utils/config/client.go:20 +0x151
main.main()
	/Users/briteming/socks5-proxy-by-yuanrenguang715/client/client.go:17 +0x27

如何解决错误

**Comment by yuanrenguang715** [comment]
无效内存地址引用，检查客户端的配置信息



---原始邮件---
发件人: "briteming"<notifications@github.com&gt;
发送时间: 2020年6月27日(周六) 中午11:55
收件人: "yuanrenguang715/socks5-proxy"<socks5-proxy@noreply.github.com&gt;;
抄送: "State change"<state_change@noreply.github.com&gt;;"Dende"<1870997052@qq.com&gt;;
主题: Re: [yuanrenguang715/socks5-proxy] go get遇错 (#1)




 
hi.
 
今天我运行程序，遇错：
 client-based-on-socks5-proxy-by-yuanrenguang715
 panic: runtime error: invalid memory address or nil pointer dereference
 [signal SIGSEGV: segmentation violation code=0x1 addr=0x1 pc=0x11fe853]
 
goroutine 1 [running]:
 github.com/go-ini/ini.(*File).SectionsByName(0x0, 0x1280367, 0x7, 0x0, 0x0, 0x0, 0x0, 0x0)
 /Users/briteming/go1.13/go/gopath/pkg/mod/github.com/go-ini/ini@v1.56.0/file.go:147 +0x73
 github.com/go-ini/ini.(*File).GetSection(...)
 /Users/briteming/go1.13/go/gopath/pkg/mod/github.com/go-ini/ini@v1.56.0/file.go:134
 github.com/go-ini/ini.(*File).Section(0x0, 0x1280367, 0x7, 0x0)
 /Users/briteming/go1.13/go/gopath/pkg/mod/github.com/go-ini/ini@v1.56.0/file.go:166 +0x43
 utils/config.ClientConfig(0xc000086058)
 /Users/briteming/socks5-proxy-by-yuanrenguang715/utils/config/client.go:20 +0x151
 main.main()
 /Users/briteming/socks5-proxy-by-yuanrenguang715/client/client.go:17 +0x27
 
如何解决错误

**Comment by briteming** [comment]
哦，
cd socks5-proxy-by-yuanrenguang715/client
然后运行：
client-based-on-socks5-proxy-by-yuanrenguang715即可。
我先前是直接在~/下运行client-based-on-socks5-proxy-by-yuanrenguang715 。因为无法读取~/socks5-proxy-by-yuanrenguang715/client/config.ini文件，所以遇错
